<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260318210312 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE task_execution (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              score SMALLINT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id UUID NOT NULL,
              task_id BIGINT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX task_execution_user_id_idx ON task_execution (user_id)');
        $this->addSql('CREATE INDEX task_execution_task_id_idx ON task_execution (task_id)');
        $this->addSql('CREATE UNIQUE INDEX task_execution_user_task_unique ON task_execution (user_id, task_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              task_execution
            ADD
              CONSTRAINT task_execution_user_id_foreign FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              task_execution
            ADD
              CONSTRAINT task_execution_task_id_foreign FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE task_execution DROP CONSTRAINT task_execution_user_id_foreign');
        $this->addSql('ALTER TABLE task_execution DROP CONSTRAINT task_execution_task_id_foreign');
        $this->addSql('DROP TABLE task_execution');
    }
}
