<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260125205028 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE lesson (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              title VARCHAR(255) NOT NULL,
              description TEXT DEFAULT NULL,
              sort SMALLINT DEFAULT 10000 NOT NULL,
              is_active BOOLEAN DEFAULT true NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              course_id INT NOT NULL,
              module_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX lesson_sort_idx ON lesson (sort)');
        $this->addSql('CREATE INDEX lesson_course_id_idx ON lesson (course_id)');
        $this->addSql('CREATE INDEX lesson_module_id_idx ON lesson (module_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              lesson
            ADD
              CONSTRAINT lesson_course_id_foreign FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              lesson
            ADD
              CONSTRAINT lesson_module_id_foreign FOREIGN KEY (module_id) REFERENCES module (id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT lesson_course_id_foreign');
        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT lesson_module_id_foreign');
        $this->addSql('DROP TABLE lesson');
    }
}
