<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\MySQLPlatform;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260402000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create messenger_messages table for Symfony Messenger failed transport';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();

        if ($platform instanceof PostgreSQLPlatform) {
            $this->addSql(<<<'SQL'
                CREATE TABLE messenger_messages (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                  body TEXT NOT NULL,
                  headers TEXT NOT NULL,
                  queue_name VARCHAR(190) NOT NULL,
                  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                  delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                  PRIMARY KEY (id)
                )
            SQL);
        } elseif ($platform instanceof MySQLPlatform) {
            $this->addSql(<<<'SQL'
                CREATE TABLE messenger_messages (
                  id BIGINT AUTO_INCREMENT NOT NULL,
                  body LONGTEXT NOT NULL,
                  headers LONGTEXT NOT NULL,
                  queue_name VARCHAR(190) NOT NULL,
                  created_at DATETIME NOT NULL,
                  available_at DATETIME NOT NULL,
                  delivered_at DATETIME DEFAULT NULL,
                  PRIMARY KEY (id)
                ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
            SQL);
        } else {
            $this->abortIf(true, sprintf('Unsupported database platform: %s', $platform::class));
        }

        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
