<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260505070033 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE agg_student_course (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              total_score NUMERIC(10, 2) DEFAULT '0' NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              student_id UUID NOT NULL,
              course_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX agg_student_course_student_id_idx ON agg_student_course (student_id)');
        $this->addSql('CREATE INDEX agg_student_course_course_id_idx ON agg_student_course (course_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX agg_student_course_student_id_course_id_unique ON agg_student_course (student_id, course_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE agg_student_module (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              total_score NUMERIC(10, 2) DEFAULT '0' NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              student_id UUID NOT NULL,
              module_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX agg_student_module_student_id_idx ON agg_student_module (student_id)');
        $this->addSql('CREATE INDEX agg_student_module_module_id_idx ON agg_student_module (module_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX agg_student_module_student_id_module_id_unique ON agg_student_module (student_id, module_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              agg_student_course
            ADD
              CONSTRAINT agg_student_course_student_id_foreign FOREIGN KEY (student_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              agg_student_course
            ADD
              CONSTRAINT agg_student_course_course_id_foreign FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              agg_student_module
            ADD
              CONSTRAINT agg_student_module_student_id_foreign FOREIGN KEY (student_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              agg_student_module
            ADD
              CONSTRAINT agg_student_module_module_id_foreign FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agg_student_course DROP CONSTRAINT agg_student_course_student_id_foreign');
        $this->addSql('ALTER TABLE agg_student_course DROP CONSTRAINT agg_student_course_course_id_foreign');
        $this->addSql('ALTER TABLE agg_student_module DROP CONSTRAINT agg_student_module_student_id_foreign');
        $this->addSql('ALTER TABLE agg_student_module DROP CONSTRAINT agg_student_module_module_id_foreign');
        $this->addSql('DROP TABLE agg_student_course');
        $this->addSql('DROP TABLE agg_student_module');
    }
}
