<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403190542 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE agg_student_lesson_skill (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              total_score NUMERIC(10, 2) DEFAULT '0' NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              student_id UUID NOT NULL,
              lesson_id INT NOT NULL,
              skill_id SMALLINT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_DDB06373CB944F1A ON agg_student_lesson_skill (student_id)');
        $this->addSql('CREATE INDEX IDX_DDB06373CDF80196 ON agg_student_lesson_skill (lesson_id)');
        $this->addSql('CREATE INDEX IDX_DDB063735585C142 ON agg_student_lesson_skill (skill_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX agg_student_lesson_skill_student_id_lesson_id_skill_id_unique ON agg_student_lesson_skill (student_id, lesson_id, skill_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              agg_student_lesson_skill
            ADD
              CONSTRAINT FK_DDB06373CB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              agg_student_lesson_skill
            ADD
              CONSTRAINT FK_DDB06373CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              agg_student_lesson_skill
            ADD
              CONSTRAINT FK_DDB063735585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agg_student_lesson_skill DROP CONSTRAINT FK_DDB06373CB944F1A');
        $this->addSql('ALTER TABLE agg_student_lesson_skill DROP CONSTRAINT FK_DDB06373CDF80196');
        $this->addSql('ALTER TABLE agg_student_lesson_skill DROP CONSTRAINT FK_DDB063735585C142');
        $this->addSql('DROP TABLE agg_student_lesson_skill');
    }
}
