<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260126105246 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE task (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              title VARCHAR(255) NOT NULL,
              description TEXT DEFAULT NULL,
              score_min SMALLINT DEFAULT 1 NOT NULL,
              score_max SMALLINT DEFAULT 10 NOT NULL,
              sort SMALLINT DEFAULT 10000 NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              lesson_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX task_sort_idx ON task (sort)');
        $this->addSql('CREATE INDEX task_lesson_id_idx ON task (lesson_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              task
            ADD
              CONSTRAINT task_lesson_id_foreign FOREIGN KEY (lesson_id) REFERENCES lesson (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE task DROP CONSTRAINT task_lesson_id_foreign');
        $this->addSql('DROP TABLE task');
    }
}
